POST http://localhost:8080/users
Content-Type: application/json

{
    "user_id" : 1,
    "name" : "Bob",
    "email" : "bob1@gmail.com",
    "password" : "abc123",
    "role" : "ROLE_PLAYER",
    "country" : "Bob_Country",
    "elo_rating" : 100,
    "rank" : "UNRANKED"

}

### 
POST http://localhost:8080/users
Content-Type: application/json

{
    "user_id" : 2,
    "name" : "Murga",
    "email" : "murga@gmail.com",
    "password" : "abc1234",
    "role" : "ROLE_ADMIN",
    "country" : "Murga_Country",
    "elo_rating" : 1000,
    "rank" : "GOLD"

}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "user_id" : 1,
    "name" : "Jack",
    "email" : "jack@gmail.com",
    "password" : "abc1234",
    "role" : "ROLE_ADMIN",
    "country" : "Murga_Country",
    "elo_rating" : 1000,
    "rank" : "GOLD"
}

###
DELETE http://localhost:8080/users/2

