###
POST http://localhost:8080/users
Content-Type: application/json

{
    "userId": 1,
    "name": "Bob",
    "email": "bob@gmail.com",
    "password": "abc123",
    "role": "ROLE_ADMIN",
    "country": "Pakistan",
    "elo_rating": 100,
    "rank": "UNRANKED"
}