POST http://localhost:8080/clans
Content-Type: application/json

{
    "clanName" : "Kai"
}

### 
POST http://localhost:8080/clans
Content-Type: application/json

{
    "clanName" : "Aether"
}

###
GET http://localhost:8080/clans

###
GET http://localhost:8080/clans/4

###
PUT http://localhost:8080/clans/1
Content-Type: application/json

{
    "clanName" : "Inferno"
}

###
DELETE http://localhost:8080/clans/1

