POST http://localhost:8080/clans
Content-Type: application/json

{
    "clanName" : "Ivies"
}

### 
POST http://localhost:8080/clans
Content-Type: application/json

{
    "clanName" : "Xolo"
}

###
GET http://localhost:8080/clans

###
GET http://localhost:8080/clans/9

###
PUT http://localhost:8080/clans/2
Content-Type: application/json

{
    "clanName" : "Kai so Kai"
}

###
DELETE http://localhost:8080/clans/2

